name: Foo

# permissions:
#   id-token: write
#   contents: write

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: BlablaSomething
      run: |
        echo BlablaSomething...

    - name: Build
      run: |
        echo build...
