name: Foo
description: Foo

runs:
  using: "composite"
  steps:

  - name: SayFoo
    shell: bash
    run: echo Foo Foo

  - name: SayBla
    shell: bash
    run: echo Bla bla ${{ secrets.ENV_PUB_KEY }}
