name: Foo
description: Foo

inputs:
  ENV_PUB_KEY:
    required: true
    description: "ENV_PUB_KEY...."

runs:
  using: "composite"
  steps:

  - name: SayFoo
    shell: bash
    run: echo Foo Foo

  - name: SayBla
    shell: bash
    run: echo Bla bla ${{ inputs.ENV_PUB_KEY }}